export const destinations = [
    {
        id: 1,
        image: "/assets/images/destinations/munnar-circle.png",
        imageDetail: "/assets/images/destinations/munnar-detail.jpg",
        altText: "Munnar",
        slug: "munnar",
        name: "Munnar",
        description : "" ,
        toursCount: 258,
        delay: 0,
    },
    {
        id: 2,
        image:"/assets/images/destinations/alappuzha-cirlce.png",
        imageDetail: "/assets/images/destinations/alappuzha-detail.jpg",
        altText: "Alappuzha",
        slug: "alappuzha",
        name: "Alappuzha",
        description : "" ,
        toursCount: 258,
        delay: 50,
    },
    {
        id: 3,
        image: "/assets/images/destinations/varkala-circle.png",
        imageDetail: "/assets/images/destinations/varkala-detail.jpg",
        altText: "Varkala",
        slug: "varkala",
        name: "Varkala",
        description : "" ,
        toursCount: 258,
        delay: 100,
    },
    {
        id: 4,
        image: "/assets/images/destinations/ooty-circle.png",
        imageDetail: "/assets/images/destinations/ooty-detail.jpg",
        altText: "Ooty",
        slug: "ooty",
        name: "Ooty",
        description : "" ,
        toursCount: 258,
        delay: 100,
    },
    {
        id: 5,
        image: "/assets/images/destinations/rameswaram-circle.png",
        imageDetail: "/assets/images/destinations/rameswaram-detail.jpg",
        altText: "Rameshwaram",
        slug: "rameshwaram",
        name: "Rameshwaram",
        description : "" ,
        toursCount: 258,
        delay: 150,
    },
    {
        id: 6,
        image: "/assets/images/destinations/Coorg-circle.png",
        imageDetail: "/assets/images/destinations/coorg-detail.jpg",
        altText: "Coorg",
        slug: "coorg",
        name: "Coorg",
        description : "" ,
        toursCount: 258,
        delay: 150,
    },
    {
        id: 7,
        image: "/assets/images/destinations/hampi-circle.png",
        imageDetail: "/assets/images/destinations/hampi-detail.jpg",
        altText: "Hampi",
        slug: "hampi",
        name: "Hampi",
        description : "" ,
        toursCount: 258,
        delay: 150,
    },
    {
        id: 8,
        image: "/assets/images/destinations/hampi-circle.png",
        altText: "Alappuzha",
        slug: "wroclaw-poland",
        name: "Wroclaw, Poland",
        description : "" ,
        toursCount: 258,
        delay: 150,
    },
    {
        id: 9,
        image: "/assets/images/destinations/hampi-circle.png",
        altText: "Alappuzha",
        slug: "france-paris",
        name: "France, Paris",
        description : "" ,
        toursCount: 258,
        delay: 150,
    },
    {
        id: 10,
        image: "/assets/images/destinations/hampi-circle.png",
        altText: "Alappuzha",
        slug: "antalya-turkey",
        name: "Antalya, Turkey",
        description : "" ,
        toursCount: 258,
        delay: 150,
    }
];
